### ISSUE TITLE
404: Not Found error

### ISSUE THREAD

**Issue by DJack93** [pfeerick/tracerWebserver#1]
Hi,

After uploading and connecting to wifi I only get: 404: Not Found in my browser. It seems as if the spiffs were not uploaded correctly.

Thanks in advance.

**Comment by pfeerick** [comment]
Did you upload the SPIFFs data? Uploading SPIFFs data is a separate step to uploading your sketch/program, just as it is with the Arduino IDE. 

What about the JSON responders, did you try one of those as they are hard-coded... as long as the server is running they should respond. 

```
  /getRatedData
  /getRealtimeData
  /getRealtimeStatus
  /getStatisticalData
  /getDiscrete
  /getCoils
```

![image](https://user-images.githubusercontent.com/5500713/63627891-ff076680-c64c-11e9-8bb3-cc2e2ee92827.png)

**Comment by DJack93** [comment]
Thanks. I was using Atom with plattformIO and couldn't see those project tasks. I'm now able to upload the SPIFFs with Visual Studio Code. And the webserver is working 👍

**Comment by pfeerick** [comment]
Excellent! :smile: I hope you find it useful! :)

Feel free to make suggestions, or submit pull requests. 

Are you interested in a version of this which also outputs to a LCD (and datalogs to SD eventually)? As if you are I'll publish the branch I'm working on which is working towards reproducing the MT50 display's overview screen.
